[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 500000
monitor_filters =
    esp32_exception_decoder

; ESP32-S3 native USB serial.  Remove this define only when using an external
; UART-to-USB adapter and configure Serial accordingly.
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D CAN_TX_PIN=48
    -D CAN_RX_PIN=47